import { SITE } from './site-meta';

// Repo where issues are filed — site-meta.ts is the single source for this.
const REPO = SITE.repoSlug;

export interface ReportIssueInput {
  title: string;
  body?: string;
  labels?: string[];
}

/**
 * Build a GitHub "new issue" URL pre-filled with the given fields. The
 * page running this code MUST be able to handle redirect navigation; we
 * return the URL string and let the caller decide window.open vs
 * location.assign.
 */
export function buildIssueUrl({ title, body = '', labels = [] }: ReportIssueInput): string {
  const params = new URLSearchParams();
  params.set('title', title);
  if (body) params.set('body', body);
  if (labels.length > 0) params.set('labels', labels.join(','));
  return `https://github.com/${REPO}/issues/new?${params.toString()}`;
}

export function openIssue(input: ReportIssueInput): void {
  if (typeof window === 'undefined') return;
  window.open(buildIssueUrl(input), '_blank', 'noopener,noreferrer');
}

/**
 * Build a body for a runtime error. Includes the error name, message,
 * stack trace (clipped to 50 lines), component path, user agent, and the
 * current URL. Safe to call on server (window/navigator guarded).
 */
export function buildErrorReportBody(args: {
  error: Error;
  componentPath?: string;
  hydrationMismatch?: boolean;
}): string {
  const { error, componentPath, hydrationMismatch } = args;
  const stack = (error.stack ?? 'no stack').split('\n').slice(0, 50).join('\n');
  return [
    '<!-- Auto-generated by FeedbackFAB error boundary -->',
    '',
    `**Type:** ${hydrationMismatch ? 'Hydration mismatch' : 'Runtime error'}`,
    `**Error:** \`${error.name}: ${error.message}\``,
    componentPath ? `**Component path:** \`${componentPath}\`` : '',
    typeof window !== 'undefined' ? `**URL:** ${window.location.href}` : '',
    typeof navigator !== 'undefined' ? `**User agent:** ${navigator.userAgent}` : '',
    '',
    '## Stack',
    '',
    '```',
    stack,
    '```',
  ]
    .filter(Boolean)
    .join('\n');
}
