blank_issues_enabled: true
contact_links:
  - name: 💬 General question or discussion
    url: https://github.com/ArtemioPadilla/zelda-wind-waker-guide/discussions
    about: For questions, ideas, or open discussions about this template
